config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  unauthenticated do
    root "users#home"
  end

  root 'groups#index', as: "moneytrack"

  resources :users

  resources :groups, only: [:index, :show, :new, :create, :destroy] do
    resources :money_tracks, only: [ :new, :show, :create, :destroy]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.role == 'admin'
      can :manage, :all
    else
      can :read, :all
      can :destroy, Group do |group|
        group.user.id == user.id
      end
      can :destroy, MoneyTrack do |money|
        money.user.id == user.id
      end
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :money_groups, dependent: :destroy
  has_many :money_tracks, through: :money_groups, dependent: :destroy

  validates :name, presence: true, length: { minimum: 3 }
end

app/models/money_group.rb
class MoneyGroup < ApplicationRecord
  belongs_to :group
  belongs_to :money_track
end

app/models/money_track.rb
class MoneyTrack < ApplicationRecord
  belongs_to :user
  has_many :money_groups, dependent: :destroy
  has_many :groups, through: :money_groups, dependent: :destroy

  validates :name, presence: true, length: { minimum: 3 }
  validates :amount, numericality: { greater_than: 0, less_than: 1_000_000 }
end

app/models/user.rb
class User < ApplicationRecord
  after_create :set_role

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups, dependent: :destroy
  has_many :money_tracks, dependent: :destroy

  validates :name, presence: true, length: { minimum: 5 }

  private

  def set_role
    update(role: 'user')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.where(user_id: current_user.id)
  end

  def show
    @group = Group.find(params[:id])
    @group_money_tracks = @group.money_tracks.all
  end

  def new
    @group = Group.new
    @icons = icons
  end

  def create
    @group = current_user.groups.create(group_params)
    if @group.save
      flash[:notice] = 'Category created successfully.'
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @group = Group.find(params[:id])
    authorize! :destroy, @group
    flash[:notice] = if @group.destroy
                       'Category removed successfully'
                     else
                       'Something went wrong'
                     end
    redirect_to root_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end

  def icons
    { 'Grocery' => 'icon0.png', 'Shopping' => 'icon1.png', 'Education' => 'icon2.png', 'Bills' => 'icon3.png',
      'Insurance' => 'icon4.png', 'Travel' => 'icon5.png' }
  end
end

app/controllers/money_tracks_controller.rb
class MoneyTracksController < ApplicationController
  def new
    @group = Group.find(params[:group_id])
    @money_track = MoneyTrack.new
  end

  def create
    @group = Group.find(params[:group_id])
    @money_track = @group.money_tracks.create(moneytrack_params)
    if @money_track.save
      flash[:notice] = 'Transaction created successfully.'
      redirect_to group_path(@group)
    else
      render :new
    end
  end

  def destroy
    @money_track = MoneyTrack.find(params[:id])
    authorize! :destroy, @money_track
    flash[:notice] = if @money_track.destroy
                       'Transaction removed successfully'
                     else
                       'Something went wrong'
                     end
    redirect_to root_path
  end

  private

  def moneytrack_params
    params.require(:money_track).permit(:name, :amount, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def home; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/money_tracks_helper.rb
module MoneyTracksHelper
end

app/views/groups/index.html.erb
<nav class="header">
  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
    <li>
    <a href="/"><i class="fa fa-navicon"></i></a>
    </li>
    <li>
      <h2 class="heading fw-bold">Categories</h2>
    </li>
    <li>
    <%= button_to destroy_user_session_path, method: :delete do %>   
      <i class="fa fa-sign-out"></i>
    <%end%>
    
   
    </li>
  </ul>
  </nav>
<%=render 'layouts/errornotice' %>
<% if @groups.any?%>
<% @groups.each do |group| %>
  <div class="p-2 m-3  category-div">
   <div class="category-info">
    <p> <%=image_tag "#{group.icon}" ,class:"p-2 m-1 rounded img-thumbnail"%></p>
    <ul class="p-2 m-1">
      <li> <p ><%= link_to group.name, group_path(group), class:"p-2 m-2 text-muted h2" %></p></li>
      <li> <p class="p-2 m-2"> <%= group.created_at.strftime("%d-%b-%Y")%></p></li>
    </ul>
    </div>
    <ul class="p-2 m-1">
    <li><p class="p-2 m-2 h3"> $<%= group.money_tracks.sum(:amount)%></p></li>
    <li>
    <%if can? :destroy, group%>
        <%=button_to "Delete", group_path(group.id), method: :delete, class:"btn btn-primary px-4 m-2"%>
      <%end%>
    </li>
    </ul>
    </div>
<%end%>
<%else%>
<p class="p-2 m-2 h3">There is no Category. You can add Category</p>
<%end%>


<div class=" w-100  py-3 px-3 btnn">
    <%= link_to "Add Category", new_group_path, class: "btn btn-outline-light  w-75 p-2"%>
</div>

app/views/groups/new.html.erb
<%= form_with model: @group, class:"input-form"  do |f|%>

  <nav class="header">
  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
    <li>
    <a href="/"><i class="fa fa-arrow-left"></i></a>
    </li>
    <li>
      <h2 class="heading fw-bold">Add Category</h2>
    </li>
    <li>
    <%= f.submit "Create Category", class:"btn btn-primary form-control" %> 
    </li>
  </ul>
  </nav>

  <div class="m-5 mb-3">
    <%= f.text_field :name,  required: true,  class:"p-2 form-control", placeholder: "Name", id:'name'%><br>
  </div>
  <div class="m-5 mb-3">
    <%= f.select :icon, options_for_select([
      ['Grocery', @icons["Grocery"]],
      ['Shopping' ,@icons["Shopping"]],
      ['Education' ,@icons["Education"]],
      ['Bills' ,@icons["Bills"]],
      ['Insurance' ,@icons["Insurance"]],
      ['Travel' ,@icons["Travel"]],
    ]),{ include_blank: "Select Icon"}, required: true , class:"form-select"%>

  </div>  
<%end%>

app/views/groups/show.html.erb
<nav class="header">
  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
    <li>
    <a href="/"><i class="fa fa-arrow-left"></i></a>
    </li>
    <li>
      <h2 class="heading fw-bold">Category Details</h2>
    </li>
    <li>
    <%= button_to destroy_user_session_path, method: :delete do %>   
      <i class="fa fa-sign-out"></i>
    <%end%>
    
   
    </li>
  </ul>
  </nav>
<%=render 'layouts/errornotice'%>
<div class="p-2 category-div">
  <div class="category-info">
    <ul class="p-2 m-2">
        <li> <p class="p-2 m-2 text-muted h2" ><%= @group.name%></p></li>
    </ul>
  </div>
  <ul class="p-2 m-2">
    <li><p class="p-2 m-2 h3"> $<%= @group.money_tracks.sum(:amount)%></p></li>
    <li>
    <%if can? :destroy, @group%>
        <%=link_to "Delete", group_path(@group.id), method: :delete, class:"btn btn-primary px-4 m-2"%>
    <%end%>
    </li>
  </ul>
</div>


 <% if @group.money_tracks.any? %>
    
    
    <% @group.money_tracks.order(created_at:'DESC').each do |fd|%>
      <div class="p-2 m-3 category-div">
        <div class="category-info">
        <p> <%=image_tag @group.icon ,class:"p-1 mx-1 mt-3 rounded img-thumbnail"%></p>
          <ul class="p-2 m-1">
            <li><p class="p-2 m-2 text-muted h2" ><%= fd.name%></p></li>
            <li> <p class="p-2 m-2"> <%= fd.created_at.strftime("%d-%b-%Y")%></p></li>
          </ul>
        </div>
        <ul class="p-2 m-1">
         <li> <p class="p-2 m-2 h4" >$<%= fd.amount%></p></li>
         <li>
          <%if can? :destroy, fd%>
          <%=button_to "Delete", group_money_track_path(group_id: @group.id, id: fd.id), method: :delete, class:"btn btn-primary px-4 m-2"%>
          <%end%>
         </li>
        </ul>
      </div>
    <%end%>
  <%else%>
      <p class="p-2 m-2 h3" >There are no transactions for this category</p>
  <%end%>


<div class="w-100 py-3 px-3 btnn">
    <%= link_to "Add transaction",  new_group_money_track_path( @group), class: "btn btn-outline-light  w-75 p-2"%>
</div>

app/views/layouts/_errornotice.html.erb
<%if notice%>
<div class="alert alert-success alert-dismissible fade show" role="alert">
<strong><%= notice %></strong>
<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<%end%>
<%if alert%>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
<strong> <%= alert %> </strong>
<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<%end%>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">

      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Budget app", "/", class: "nav-link active" %>
          </li>
          <li class="nav-item">
          <%= link_to "Catgories", groups_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
          <%= link_to "Create Category", new_group_path, class: "nav-link active" %>
          </li>
        <% end %>
      </ul>
      <div class="d-flex">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-outline-success" %>
          </li>
          <li class = "nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-outline-success" %>
          </li>
          <li class="nav-item">
            <%= link_to "#{current_user.name}", class: "btn btn-outline-success"%>
          </li>
          <% else %>
          <li class = "nav-item">
            <%= link_to "Sign In", new_user_session_path, class: "btn btn-outline-success" %>
          </li>
          <li class = "nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-outline-success" %>
          </li>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  
  </head>

  <body>

    <%= yield %>
    
  </body>
</html>

app/views/money_tracks/new.html.erb
<%=form_with model: [@group, @group.money_tracks.create], class:"input-form"  do |f|%>

  <nav class="header">
  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
    <li>
    <a href="/"><i class="fa fa-arrow-left"></i></a>
    </li>
    <li>
      <h2 class="heading fw-bold">Add Transcation</h2>
    </li>
    <li>
    <%= f.submit "Create Transaction", class:"btn btn-primary form-control" %> 
    </li>
  </ul>
  </nav>
    <%= f.hidden_field :user_id, value: current_user.id %>
  
    <div class="m-5 mb-3">
    <%= f.text_field :name,required: true, class:"p-2 form-control", placeholder: "Name", id: "name"%><br>
    </div>

    <div class="m-5 mb-3">
    <%=f.text_field :category, value:@group.name, class:"p-2 form-control"%><br>
    </div>

    <div class="m-5 mb-3">
    <%= f.number_field :amount ,  class:"p-2 form-control" , required: true, placeholder: 'Amount',  min: 1, id:"amount"%><br>
    </div>
<%end%>

app/views/users/home.html.erb
<div class = "position-relative">
  <h1 class = "text-center m-5 text-muted">Home Budget App</h1>
  <div class="sign-btn-wrapper text-center d-flex flex-column">
    <button class = 'btn btn-primary m-1'>
      <%= link_to "LOG IN", new_user_session_path, id: "loginBtn" , class:"btn btn-primary" %>
    </button>
    <button class = 'btn btn-primary m-1'>
      <%= link_to "SIGN UP", new_user_registration_path, id: "signupBtn", class:"btn btn-primary" %>
    </button>
  </div>
</div>